Task iomanip
u123056/cxx-tasks pull request #1
Opened 2018-10-28 18:25 UTC by u123056

2018-10-28 19:02 UTC, igsha requested changes
Тесты проходят, но я бы хотел увидеть некоторые изменения.  
-1 балл за недельную просрочку.

2018-10-28 19:02 UTC, igsha commented on iomanip/include/catch_reporter_automake.hpp
> +/*
Зачем эти файлы здесь? Все сторонние библиотеки (и заголовочные файлы) должны быть установлены в систему. `cmake` "видит" сторонние библиотеки через установку переменной окружения `CMAKE_PREFIX_PATH`, которая содержит абсолютный путь до директории, в которой находится `catch.hpp`. Подробнее про установку переменных окружения можно почитать [здесь](https://www.computerhope.com/issues/ch000549.htm)

2018-10-28 19:02 UTC, igsha commented on iomanip/include/catch_reporter_teamcity.hpp
> +/*
эти файлы точно не нужны, так как `catch` предоставляется одним файлом. Необходимо скачать [собранный заголовочный файл](https://github.com/philsquared/Catch/releases/download/v1.12.2/catch.hpp), а не исходники.

2018-10-28 19:02 UTC, igsha commented on iomanip/include/iomanip.hpp
> +    std::ostream & os;
Я уже видел это решение. Давайте здесь вы переместите структуру `add_proxy_next` внутрь `add_proxy`, и уберёте отсюда поле `os`, заменив его чем-то другим. `os` должен остаться только у "родителя" - `add_proxy`

2018-11-25 07:35 UTC, u123056 commented on iomanip/include/iomanip.hpp
> +    std::ostream & os;
В конце семестра буду делать изменения

2018-11-25 10:52 UTC, igsha commented
6 баллов тогда за лабораторную. Жду отдельным пул-реквестом исправления оставшихся замечаний (можно будет получить до +5 баллов).

2018-11-25 10:52 UTC, merged