Сребницкий Георгий
u123056/cxx-tasks pull request #2
Opened 2018-11-11 11:20 UTC by u123056

2018-11-11 11:57 UTC, igsha requested changes
Требуются доработки. Так как сдача лабораторной отстаёт на 2 недели, максимальное количество баллов снижается на 2.

2018-11-11 11:57 UTC, igsha commented on proxy/include/proxy.hpp
> +using namespace std;
так плохо писать: я теперь не смогу создать свои классы `mutext` или `thread`. Подключать всё пространство имён можно **только** в cpp-файлах, а не в заголовочных.

2018-11-11 11:57 UTC, igsha commented on proxy/include/proxy.hpp
> +        return proxy(ptr_, ref(mutex_));
зачем здесь `ref`? Как он помогает?

2018-11-11 11:57 UTC, igsha commented on proxy/include/proxy.hpp
> +        mutex &mutex_;
я уже видел такое решение. Давайте здесь будем хранить не ссылку на мьютекс, а сам локер. При освобождении объекта, локер сам освободится, т.е., никаких деструкторов писать не нужно. Нужно только грамотно передать локер в этот класс.

2018-11-15 15:04 UTC, u123056 commented on proxy/include/proxy.hpp
> +        return proxy(ptr_, ref(mutex_));
Без использования ref создастся копия мьютекса и она залочится вместо самого мьютекса

2018-11-15 16:23 UTC, igsha commented on proxy/include/proxy.hpp
> +        return proxy(ptr_, ref(mutex_));
не верю: в классе и его конструкторе передаётся ссылка, а не сам объект. Никакой копии не создаётся, только копия ссылки

2018-11-25 07:34 UTC, u123056 commented on proxy/include/proxy.hpp
> +        mutex &mutex_;
В конце семестра буду делать изменения

2018-11-25 10:50 UTC, igsha commented
Ок, тогда за эту лабораторную будет 6 баллов. Ещё +4 балла можно будет получить в конце семестра после устранения всех недочётов отдельным пул-реквестом.

2018-11-25 10:50 UTC, merged