Лабораторная type_map
u123056/cxx-tasks pull request #6
Opened 2018-12-02 20:53 UTC by u123056

```
    Start 1: tests_type_map:type_map::int
1/2 Test #1: tests_type_map:type_map::int .....   Passed    0.00 sec
    Start 2: tests_type_map:type_map::enum
2/2 Test #2: tests_type_map:type_map::enum ....   Passed    0.00 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
tests_type_map    =   0.00 sec*proc (2 tests)

```

2018-12-03 05:29 UTC, igsha requested changes
Пойдёт в качестве лабораторной №4.
-3 балла за просрок.

2018-12-03 05:29 UTC, igsha commented on type_map/include/type_map.hpp
> +        return (*this)[detail::type_to_index<T, types>().v];
Поле `v` статическое, его можно получить, не создавая объект `type_to_index<T, types>`

2018-12-03 05:29 UTC, igsha commented on type_map/include/type_map.hpp
> +        return (*this)[detail::type_to_index<T, types>().v];
Один из методов `as` можно реализовать через другой, чтобы избежать копи-пастов

2018-12-03 05:29 UTC, igsha commented on type_map/include/type_map.hpp
> +    const auto& get(TypeMap& tm)
Не собирается:
```
/tmp/cxx-tasks/type_map/tests/type_map.cpp:53:30: error: assignment of read-only location ‘std::get<float, type_map<int, int, float, unsigned char> >(m)’
         std::get<float>(m) = 42;
```

2018-12-16 16:18 UTC, u123056 commented
@igsha, замечания исправил

2018-12-16 17:50 UTC, igsha requested changes

2018-12-16 17:50 UTC, igsha commented on type_map/include/type_map.hpp
>      const auto& get(const TypeMap& tm)
У меня всё ещё ошибки:
```
/tmp/cxx-tasks/type_map/tests/type_map.cpp:53:30: error: assignment of read-only location ‘std::get<float, type_map<int, int, float, unsigned char> >(m)’
         std::get<float>(m) = 42;
                              ^~
```
Сигнатура неправильная, здесь не должно быть константности нигде.

2018-12-25 15:31 UTC, igsha approved these changes

2018-12-25 15:32 UTC, merged