Лабораторная variant
u123056/cxx-tasks pull request #7
Opened 2018-12-02 23:21 UTC by u123056

```
Start 1: tests_variant:variant::number
1/5 Test #1: tests_variant:variant::number .............   Passed    0.00 sec
    Start 2: tests_variant:variant::array
2/5 Test #2: tests_variant:variant::array ..............   Passed    0.00 sec
    Start 3: tests_variant:variant::recursive_array
3/5 Test #3: tests_variant:variant::recursive_array ....   Passed    0.00 sec
    Start 4: tests_variant:variant::recursive_array2
4/5 Test #4: tests_variant:variant::recursive_array2 ...   Passed    0.00 sec
    Start 5: tests_variant:variant::recursive_map
5/5 Test #5: tests_variant:variant::recursive_map ......   Passed    0.00 sec

100% tests passed, 0 tests failed out of 5

Label Time Summary:
tests_variant    =   0.01 sec*proc (5 tests)

Total Test time (real) =   0.01 sec
```

2018-12-03 05:40 UTC, igsha requested changes
Необходимы доработки. Засчитаю это за лабораторную №5. Пул-реквест был сделан на 15 неделе, поэтому -3 балла за просрок.

2018-12-03 05:40 UTC, igsha commented on variant/include/variant.hpp
> +    using std::vector<std::variant<number, std::shared_ptr<recursive_array>>>::vector;
Базовый класс уже в области видимости, нет необходимости писать заново весь этот шаблон
```
using vector::vector;
```

2018-12-03 05:40 UTC, igsha commented on variant/include/variant.hpp
> +#include <any>
и где он используется?

2018-12-03 05:40 UTC, igsha commented on variant/include/variant.hpp
> +	using std::map<std::string, variant_decorator< int, bool, std::string,  boost::recursive_wrapper< recursive_map >>>::map;
Гораздо проще было бы написать `using map::map`. В лекциях про это было.

2018-12-03 05:40 UTC, igsha commented on variant/include/variant.hpp
> +		return const_cast<T>(this->as<T>());
Не
```
/tmp/cxx-tasks/variant/tests/variant.cpp:60:9:   required from here
/tmp/cxx-tasks/variant/include/variant.hpp:54:10: error: invalid use of const_cast with type ‘int’, which is not a pointer, reference, nor a pointer-to-data-member type
   return const_cast<T>(this->as<T>());
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
`this` - это константа, его нельзя приводить к мутабельной ссылке. Мутабельный объект, напротив, можно без проблем приводить к константе.

2018-12-16 13:04 UTC, u123056 commented
@igsha, замечания исправил

2018-12-16 13:35 UTC, igsha approved these changes

2018-12-16 13:35 UTC, merged