Лабораторная csv parser
u123056/cxx-tasks pull request #8
Opened 2018-12-02 23:38 UTC by u123056

```
      Start  1: tests_parser:csv::string
 1/10 Test  #1: tests_parser:csv::string ..............   Passed    0.00 sec
      Start  2: tests_parser:csv::cell
 2/10 Test  #2: tests_parser:csv::cell ................   Passed    0.00 sec
      Start  3: tests_parser:csv::row
 3/10 Test  #3: tests_parser:csv::row .................   Passed    0.00 sec
      Start  4: tests_parser:csv::csv
 4/10 Test  #4: tests_parser:csv::csv .................   Passed    0.00 sec
      Start  5: tests_parser:csv::operator_csv
 5/10 Test  #5: tests_parser:csv::operator_csv ........   Passed    0.00 sec
      Start  6: tests_parser:quoted_string::spaces
 6/10 Test  #6: tests_parser:quoted_string::spaces ....   Passed    0.00 sec
      Start  7: tests_parser:quoted_string::comma
 7/10 Test  #7: tests_parser:quoted_string::comma .....   Passed    0.00 sec
      Start  8: tests_parser:quoted_string::quote
 8/10 Test  #8: tests_parser:quoted_string::quote .....   Passed    0.00 sec
      Start  9: tests_parser:quoted_string::newline
 9/10 Test  #9: tests_parser:quoted_string::newline ...   Passed    0.00 sec
      Start 10: tests_parser:quoted_string::failure
10/10 Test #10: tests_parser:quoted_string::failure ...   Passed    0.00 sec

100% tests passed, 0 tests failed out of 10

Label Time Summary:
!mayfail        =   0.01 sec*proc (3 tests)
tests_parser    =   0.02 sec*proc (10 tests)

Total Test time (real) =   0.02 sec

```

2018-12-03 05:44 UTC, igsha requested changes
Необходимы доработки. Засчитаю в качестве лабораторной №6.
-2 балла за просрок.

2018-12-03 05:44 UTC, igsha commented on parser/include/csv.hpp
> +            return parser::load_from_string<types::csv::csv>(s, parser::csv::csv);
Параметр `size` не используется, это приведёт к предупреждению со стороны компилятора. Так как `s` может не содержать нулевой символ, всё это дело может развалиться

2018-12-16 12:51 UTC, u123056 commented
@igsha, исправил замечания

2018-12-16 13:33 UTC, igsha commented
@u123056, всё сломалось, так как в одном из мёржей был один и тот же код. Надо сделать рибейз ветки от своего мастера.

2018-12-16 16:13 UTC, u123056 commented
@igsha, починил

2018-12-16 17:41 UTC, igsha approved these changes

2018-12-16 17:41 UTC, merged